### ISSUE TITLE
Bug when displaying error dialog on customer

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#367]
To recreate the thrown exception try to scan product which doesn't exist in the database.

Exception info:

Apr 09, 2017 11:08:09 AM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method smartcodeScanned(UtilsContracts.SmartcodeScanEvent) on subscriber CustomerGuiScreens.CustomerMainScreen@30689092 when dispatching event: UtilsContracts.SmartcodeScanEvent@794fe647
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-4
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Stage.<init>(Stage.java:241)
	at javafx.stage.Stage.<init>(Stage.java:227)
	at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.Dialog.<init>(Dialog.java:263)
	at javafx.scene.control.Alert.<init>(Alert.java:245)
	at javafx.scene.control.Alert.<init>(Alert.java:223)
	at GuiUtils.DialogMessagesService.alertCreator(DialogMessagesService.java:33)
	at GuiUtils.DialogMessagesService.showErrorDialog(DialogMessagesService.java:24)
	at CustomerGuiHelpers.CustomerGuiExceptionsHandler.handle(CustomerGuiExceptionsHandler.java:39)
	at CustomerGuiScreens.CustomerMainScreen.smartcodeScannedHandler(CustomerMainScreen.java:308)
	at CustomerGuiScreens.CustomerMainScreen.smartcodeScanned(CustomerMainScreen.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:76)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:119)
	at com.google.common.eventbus.EventBus.post(EventBus.java:215)
	at UtilsImplementations.BarcodeEventHandler$BarcodeListener.run(BarcodeEventHandler.java:59)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AviadCo** [comment]
@shimonAzulay 
Did this bug happened in the worker?
@IdanAtias @LiorBenAmi 
Do you remember if we checked the full flow from GUI for product which doesn't exist in the system?

**Comment by IdanAtias** [comment]
Not sure, don't think so.

**Comment by AviadCo** [comment]
Failed to recreate bug... closed for now.
