### ISSUE TITLE
Employee run throws exception

### ISSUE THREAD

**Issue by OriRoth** [TechnionYP5777/SmartCity-Market#577]
```Java
1. EmployeeGuiPreloader constructor called, thread: JavaFX Application Thread
2. EmployeeGuiPreloader#init, thread: JavaFX-Launcher
3. EmployeeApplicationScreen#start (showing preloader stage), thread: JavaFX Application Thread
4. BEFORE_LOAD
5. BEFORE_INIT
6. EmployeeApplicationScreen#init (doing some heavy lifting), thread: JavaFX-Launcher
7. BEFORE_START
2017-07-03 13:36:57 FATAL AbstractApplicationScreen:67 - 
/home/ori/Desktop/SmartCity-Market/Employee/target/classes/EmployeeMainScreen/EmployeeMainScreen.fxml

2017-07-03 13:36:57 FATAL AbstractApplicationScreen:68 - javafx.fxml.LoadException: 
/home/ori/Desktop/SmartCity-Market/Employee/target/classes/EmployeeMainScreen/EmployeeMainScreen.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3214)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
	at GuiUtils.AbstractApplicationScreen.setScene(AbstractApplicationScreen.java:65)
	at EmployeeGui.EmployeeApplicationScreen.start(EmployeeApplicationScreen.java:47)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
	at EmployeeGui.EmployeeMainScreen.initialize(EmployeeMainScreen.java:45)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	... 18 more
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
	... 21 more

```

**Comment by OriRoth** [comment]
The vid runs fine thugh, when activating from the package explorer.

**Comment by IdanAtias** [comment]
After this exception is thrown the app continues to the login screen?

In what java version u use?

(It is because something not right with the Player plugin u use. It should be OK if doing all the steps in installme wiki)

**Comment by OriRoth** [comment]
1.8

**Comment by OriRoth** [comment]
Just blank Smart Market Beta window

**Comment by OriRoth** [comment]
I did all the steps! What plugin are you talking about? I can check its version.

**Comment by IdanAtias** [comment]
what is your ubuntu version ?

**Comment by OriRoth** [comment]
17.04

**Comment by IdanAtias** [comment]
As for ubuntun 14.04 all that is needed is to have the latest JDK.
I believe it is the same for ubuntu 17.04.
Plz try the following:
in http://www.ubuntuupdates.org/. Search for packages libavutil51, libavformat53, libavcodec53

Download the ones matches the architecture of your JVM and use sudo dpkg -i libav*.deb to install them.

**Comment by IdanAtias** [comment]
If it doesn't help, re-open this issue.
tnx.

**Comment by OriRoth** [comment]
Sorry, too complicated for me.
